### ISSUE TITLE
请问代码中的关系超图注意力是只使用了一层吗？可以改为多层注意力吗？

### ISSUE THREAD

**Issue by Allan-waker** [xlxwalex/HyCxG#3]

**Comment by xlxwalex** [comment]
你好，

是的，我们的代码里使用了单层的。你可以通过修改超参数把它改为多层使用。

**Comment by Allan-waker** [comment]
请问是修改哪一个超参呢？您测试过不同层的效果吗？单层的效果是最好的吗？

**Comment by xlxwalex** [comment]
可以修改该行的超参数：https://github.com/xlxwalex/HyCxG/blob/712c85c99ea073886196d7791a3b0c13379fd946/HyCxG/config.py#L30

我没有对每个任务做过对比，不过在ABSA上基本上单层性能要更好。因为我们在取cxs的时候有一步离线的选择优化，因此单层的就足够了。如果你不需要/没有使用启发式搜索这步的话，可以增加层数应该会比较有效。

**Comment by Allan-waker** [comment]
好的，感谢解答！

**Comment by xlxwalex** [comment]
客气啦：）
